name:                wyag-hs
version:             0.1.0.0
github:              "quasarbright/wyag-hs"
license:             BSD3
author:              "Mike Delmonaco"
maintainer:          "mdelmonacochs@gmail.com"
copyright:           "Mike Delmonaco"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/quasarbright/wyag-hs#readme>

dependencies:
- base >= 4.7 && < 5
- zlib
- cryptohash
- filepath
- optparse-applicative

executables:
  wyag-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - wyag-hs

library:
  source-dirs: src
  ghc-options:
  - -Wall

tests:
  wyag-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - wyag-hs
